CREATE TABLE patient (
    userID INT AUTO_INCREMENT,
    nameP VARCHAR(45) NOT NULL,
    surnameP VARCHAR(45) NOT NULL,
    emailP VARCHAR(45) NOT NULL UNIQUE,
    password VARCHAR(45) NOT NULL,
    PRIMARY KEY (userID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Doctor (
	doctorID INT AUTO_INCREMENT,
    nameD VARCHAR (45) NOT NULL,
    surnameD VARCHAR (45) NOT NULL,
    specialty VARCHAR (45) NOT NULL,
    addressD VARCHAR (45) NOT NULL,
    phoneD VARCHAR (45) NOT NULL,
    detailsD VARCHAR(256),
    PRIMARY KEY (doctorID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE Appointment (
	appointmentID INT AUTO_INCREMENT,
    appointmentDate DATE NOT NULL,
    appointmentTime TIME NOT NULL,
    userID INT NOT NULL,
    doctorID INT NOT NULL,
    PRIMARY KEY (appointmentID),
    FOREIGN KEY (userID) REFERENCES Patient(userID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (doctorID) REFERENCES Doctor (doctorID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    
CREATE TABLE Review (
	reviewID INT AUTO_INCREMENT,
    reviewDate DATETIME NOT NULL,
    rate INT ,
    comment VARCHAR(256),
	userID INT NOT NULL,
    doctorID INT NOT NULL,
    PRIMARY KEY (reviewID),
    FOREIGN KEY (userID) REFERENCES Patient(userID) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (doctorID) REFERENCES Doctor (doctorID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;